remember:
  me:
    token:
      key: "Fasadas231231@#$%^&asadassv324234352353adasda!@#$%^"
      expiry: 30

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/super_trello?currentSchema=trello
    username: postgres
    password: 5654

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  banner:
    image:
      location: classpath:banner.txt
server:
  port: 9090